name: Build Image and Push to Quay

on: push

jobs:
  Security:
    name: Security Pipeline
    uses: uc-cdis/.github/.github/workflows/securitypipeline.yaml@master
    with:
      python-poetry: 'false'
    secrets: inherit #pragma: allowlist secret

  build-amd64:
    name: Build AMD64 Image
    uses: uc-cdis/.github/.github/workflows/image_build_push.yaml@master
    with:
      USE_QUAY_ONLY: true
      BUILD_PLATFORMS: "linux/amd64"
      OVERRIDE_TAG_NAME: "${{ github.ref_name }}-amd64"
    secrets:
      ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
      ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}

  build-arm64:
    name: Build ARM64 Image
    uses: uc-cdis/.github/.github/workflows/image_build_push.yaml@master
    with:
      USE_QUAY_ONLY: true
      BUILD_PLATFORMS: "linux/arm64"
      OVERRIDE_TAG_NAME: "${{ github.ref_name }}-arm64"
    secrets:
      ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
      ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}

  create-manifest:
    name: Create Multi-arch Manifest
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Create and push manifest
        run: |
          docker manifest create \
            quay.io/cdis/mmrf-data-commons:${{ github.ref_name }} \
            quay.io/cdis/mmrf-data-commons:${{ github.ref_name }}-amd64 \
            quay.io/cdis/mmrf-data-commons:${{ github.ref_name }}-arm64

          docker manifest push quay.io/cdis/mmrf-data-commons:${{ github.ref_name }}
